### PR TITLE
add line numbers to formatted json

### LINKED ISSUE #1: Add line numbers to lines
`Note:` It shouldn't be hardcoded but be generated automatically for every line.
Number each line like this. 
image

### PR DESCRIPTION
**Pull request by metal-oopa**
Closes https://github.com/nirajacharyaa/JSONformatter/issues/1

The following is what formatted JSON currently looks like: 
image

The line numbers are evenly spaced for all lines.

### CODE REVIEW

**Comment by nirajacharyaa** [comment]
You have done great work, but I didn't mean that way. I meant like an editor, how you press enter and the line number gets generated. Also, there is another problem with your solution If I copy the numbers will also be copied. You can refer to this [article](https://medium.com/weekly-webtips/enable-line-numbering-to-any-html-textarea-35e15ea320e2), fix it and I will merge it.

**Comment by metal-oopa** [comment]
> You have done great work, but I didn't mean that way. I meant like an editor, how you press enter and the line number gets generated. Also, there is another problem with your solution If I copy the numbers will also be copied. You can refer to this [article](https://medium.com/weekly-webtips/enable-line-numbering-to-any-html-textarea-35e15ea320e2), fix it and I will merge it.

Thanks for the clarification. I will update the code right away.

**Comment by metal-oopa** [comment]
Hey @nirajacharyaa 

This is how the line Counter looks now: 
image

Additional issues solved:
1. Numbers don't get copied anymore.

**Comment by nirajacharyaa** [comment]
Great work, keep contributing. Happy Hacktoberfest 🍾

**Pull request merged**
